import path from "node:path";
import { stringify } from "csv-stringify/sync";
import { PATHS } from "../src/config.js";
import {
  ensureDir,
  log,
  nowIso,
  readJson,
  writeJson,
  writeText,
} from "../src/lib/io.js";
import type { NormalizedDataset } from "../src/types.js";

function sqlQuote(value: string | null | undefined): string {
  if (value === null || value === undefined) return "NULL";
  return `'${String(value).replace(/'/g, "''")}'`;
}

function sqlBool(v: boolean): string {
  return v ? "TRUE" : "FALSE";
}

function sqlNum(v: number | null | undefined): string {
  if (v === null || v === undefined || Number.isNaN(v)) return "NULL";
  return String(v);
}

async function main() {
  log("export:supabase", "Generating Supabase-ready export files (no remote upload)");
  await ensureDir(PATHS.dataExports);
  await ensureDir(path.join(PATHS.dataExports, "supabase"));

  const dataset = await readJson<NormalizedDataset>(
    path.join(PATHS.dataNormalized, "dataset.json"),
  );
  if (!dataset) throw new Error("Missing normalized dataset");

  // JSON exports
  await writeJson(path.join(PATHS.dataExports, "products.json"), dataset.products);
  await writeJson(path.join(PATHS.dataExports, "categories.json"), dataset.categories);
  await writeJson(path.join(PATHS.dataExports, "brands.json"), dataset.brands);
  await writeJson(path.join(PATHS.dataExports, "markets.json"), dataset.markets);
  await writeJson(path.join(PATHS.dataExports, "media.json"), dataset.media);
  await writeJson(path.join(PATHS.dataExports, "documents.json"), dataset.documents);
  await writeJson(path.join(PATHS.dataExports, "attributes.json"), dataset.attributes);
  await writeJson(path.join(PATHS.dataExports, "dataset.json"), dataset);

  // CSV products
  const productRows = dataset.products.map((p) => ({
    id: p.id,
    source_id: p.source_id,
    sku: p.sku ?? "",
    name: p.name,
    slug: p.slug,
    brand_id: p.brand_id ?? "",
    product_type_id: p.product_type_id ?? "",
    original_url: p.original_url,
    source_active: p.source_active,
    content_hash: p.content_hash,
    first_seen_at: p.first_seen_at,
    last_seen_at: p.last_seen_at,
    description: p.description,
  }));
  await writeText(
    path.join(PATHS.dataExports, "products.csv"),
    stringify(productRows, { header: true }),
  );

  // Seed SQL (INSERT statements) — for later import
  const lines: string[] = [];
  lines.push("-- Generated by npm run export:supabase");
  lines.push(`-- generated_at: ${nowIso()}`);
  lines.push("-- Does NOT upload to Supabase. Apply manually after schema.");
  lines.push("BEGIN;");
  lines.push("");

  for (const c of dataset.categories) {
    lines.push(
      `INSERT INTO categories (id, parent_id, name, slug, description, image_id, sort_order, active, source_id) VALUES (${sqlQuote(c.id)}, ${sqlQuote(c.parent_id)}, ${sqlQuote(c.name)}, ${sqlQuote(c.slug)}, ${sqlQuote(c.description)}, ${sqlQuote(c.image_id)}, ${sqlNum(c.sort_order)}, ${sqlBool(c.active)}, ${sqlQuote(c.source_id)}) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, updated_at = now();`,
    );
  }
  for (const b of dataset.brands) {
    lines.push(
      `INSERT INTO brands (id, name, slug, description, logo_media_id, active, source_id) VALUES (${sqlQuote(b.id)}, ${sqlQuote(b.name)}, ${sqlQuote(b.slug)}, ${sqlQuote(b.description)}, ${sqlQuote(b.logo_media_id)}, ${sqlBool(b.active)}, ${sqlQuote(b.source_id)}) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, updated_at = now();`,
    );
  }
  for (const m of dataset.markets) {
    lines.push(
      `INSERT INTO markets (id, name, slug, description, source_id) VALUES (${sqlQuote(m.id)}, ${sqlQuote(m.name)}, ${sqlQuote(m.slug)}, ${sqlQuote(m.description)}, ${sqlQuote(m.source_id)}) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name;`,
    );
  }
  for (const t of dataset.product_types) {
    lines.push(
      `INSERT INTO product_types (id, name, slug, source_id) VALUES (${sqlQuote(t.id)}, ${sqlQuote(t.name)}, ${sqlQuote(t.slug)}, ${sqlQuote(t.source_id)}) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name;`,
    );
  }
  for (const a of dataset.attributes) {
    lines.push(
      `INSERT INTO attributes (id, name, slug, data_type, unit, filterable) VALUES (${sqlQuote(a.id)}, ${sqlQuote(a.name)}, ${sqlQuote(a.slug)}, ${sqlQuote(a.data_type)}, ${sqlQuote(a.unit)}, ${sqlBool(a.filterable)}) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name;`,
    );
  }
  for (const m of dataset.media) {
    lines.push(
      `INSERT INTO media (id, type, filename, mime_type, original_url, local_path, storage_path, width, height, file_size, checksum, alt_text, created_at) VALUES (${sqlQuote(m.id)}, ${sqlQuote(m.type)}, ${sqlQuote(m.filename)}, ${sqlQuote(m.mime_type)}, ${sqlQuote(m.original_url)}, ${sqlQuote(m.local_path)}, ${sqlQuote(m.storage_path)}, ${sqlNum(m.width)}, ${sqlNum(m.height)}, ${sqlNum(m.file_size)}, ${sqlQuote(m.checksum)}, ${sqlQuote(m.alt_text)}, ${sqlQuote(m.created_at)}) ON CONFLICT (id) DO UPDATE SET checksum = EXCLUDED.checksum, file_size = EXCLUDED.file_size, local_path = EXCLUDED.local_path, storage_path = EXCLUDED.storage_path;`,
    );
  }
  for (const p of dataset.products) {
    lines.push(
      `INSERT INTO products (id, source_id, sku, name, slug, short_description, description, status, brand_id, product_type_id, original_url, featured_image_id, seo_title, seo_description, source_created_at, source_updated_at, source_active, first_seen_at, last_seen_at, content_hash, purchasable, featured, published, sort_order, created_at, updated_at) VALUES (${sqlQuote(p.id)}, ${sqlQuote(p.source_id)}, ${sqlQuote(p.sku)}, ${sqlQuote(p.name)}, ${sqlQuote(p.slug)}, ${sqlQuote(p.short_description)}, ${sqlQuote(p.description)}, ${sqlQuote(p.status)}, ${sqlQuote(p.brand_id)}, ${sqlQuote(p.product_type_id)}, ${sqlQuote(p.original_url)}, ${sqlQuote(p.featured_image_id)}, ${sqlQuote(p.seo_title)}, ${sqlQuote(p.seo_description)}, ${sqlQuote(p.source_created_at)}, ${sqlQuote(p.source_updated_at)}, ${sqlBool(p.source_active)}, ${sqlQuote(p.first_seen_at)}, ${sqlQuote(p.last_seen_at)}, ${sqlQuote(p.content_hash)}, ${sqlBool(p.purchasable)}, ${sqlBool(p.featured)}, ${sqlBool(p.published)}, ${sqlNum(p.sort_order)}, ${sqlQuote(p.created_at)}, ${sqlQuote(p.updated_at)}) ON CONFLICT (source_id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, content_hash = EXCLUDED.content_hash, source_active = EXCLUDED.source_active, last_seen_at = EXCLUDED.last_seen_at, updated_at = now();`,
    );
  }
  for (const pc of dataset.product_categories) {
    lines.push(
      `INSERT INTO product_categories (product_id, category_id, is_primary) VALUES (${sqlQuote(pc.product_id)}, ${sqlQuote(pc.category_id)}, ${sqlBool(pc.is_primary)}) ON CONFLICT (product_id, category_id) DO UPDATE SET is_primary = EXCLUDED.is_primary;`,
    );
  }
  for (const pm of dataset.product_markets) {
    lines.push(
      `INSERT INTO product_markets (product_id, market_id) VALUES (${sqlQuote(pm.product_id)}, ${sqlQuote(pm.market_id)}) ON CONFLICT (product_id, market_id) DO NOTHING;`,
    );
  }
  for (const pm of dataset.product_media) {
    lines.push(
      `INSERT INTO product_media (product_id, media_id, role, sort_order) VALUES (${sqlQuote(pm.product_id)}, ${sqlQuote(pm.media_id)}, ${sqlQuote(pm.role)}, ${sqlNum(pm.sort_order)}) ON CONFLICT (product_id, media_id, role) DO UPDATE SET sort_order = EXCLUDED.sort_order;`,
    );
  }
  for (const d of dataset.documents) {
    lines.push(
      `INSERT INTO documents (id, product_id, name, document_type, original_url, local_path, storage_path, mime_type, checksum) VALUES (${sqlQuote(d.id)}, ${sqlQuote(d.product_id)}, ${sqlQuote(d.name)}, ${sqlQuote(d.document_type)}, ${sqlQuote(d.original_url)}, ${sqlQuote(d.local_path)}, ${sqlQuote(d.storage_path)}, ${sqlQuote(d.mime_type)}, ${sqlQuote(d.checksum)}) ON CONFLICT (id) DO UPDATE SET checksum = EXCLUDED.checksum, local_path = EXCLUDED.local_path;`,
    );
  }
  for (const v of dataset.product_attribute_values) {
    lines.push(
      `INSERT INTO product_attribute_values (product_id, attribute_id, value_text, value_number, value_boolean, value_json) VALUES (${sqlQuote(v.product_id)}, ${sqlQuote(v.attribute_id)}, ${sqlQuote(v.value_text)}, ${sqlNum(v.value_number)}, ${v.value_boolean === null || v.value_boolean === undefined ? "NULL" : sqlBool(v.value_boolean)}, ${v.value_json === null || v.value_json === undefined ? "NULL" : sqlQuote(JSON.stringify(v.value_json))}::jsonb);`,
    );
  }
  for (const v of dataset.product_variants) {
    lines.push(
      `INSERT INTO product_variants (id, product_id, sku, name, active, sort_order) VALUES (${sqlQuote(v.id)}, ${sqlQuote(v.product_id)}, ${sqlQuote(v.sku)}, ${sqlQuote(v.name)}, ${sqlBool(v.active)}, ${sqlNum(v.sort_order)}) ON CONFLICT (id) DO UPDATE SET sku = EXCLUDED.sku, name = EXCLUDED.name, active = EXCLUDED.active;`,
    );
  }

  lines.push("COMMIT;");
  await writeText(
    path.join(PATHS.dataExports, "supabase", "seed.sql"),
    lines.join("\n") + "\n",
  );

  // Manifest for Storage upload later
  await writeJson(path.join(PATHS.dataExports, "supabase", "storage-manifest.json"), {
    generated_at: nowIso(),
    buckets: {
      "product-images": dataset.media
        .filter((m) => m.role_hint === "featured")
        .map((m) => ({
          local_path: m.local_path,
          storage_path: m.storage_path,
          original_url: m.original_url,
          checksum: m.checksum,
        })),
      "product-documents": dataset.media
        .filter((m) => m.role_hint === "technical")
        .map((m) => ({
          local_path: m.local_path,
          storage_path: m.storage_path,
          original_url: m.original_url,
          checksum: m.checksum,
        })),
    },
    note: "Upload later with Supabase Storage API/CLI. Do not invent public URLs.",
  });

  await writeJson(path.join(PATHS.reports, "export-report.json"), {
    generated_at: nowIso(),
    outputs: [
      "data/exports/products.json",
      "data/exports/products.csv",
      "data/exports/categories.json",
      "data/exports/brands.json",
      "data/exports/media.json",
      "data/exports/documents.json",
      "data/exports/supabase/seed.sql",
      "data/exports/supabase/storage-manifest.json",
    ],
    product_count: dataset.products.length,
  });

  log("export:supabase", "Export ready (local only)", {
    seed: "data/exports/supabase/seed.sql",
    products: dataset.products.length,
  });
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
